apiVersion: v1
kind: Secret
metadata:
  name: mcp-runescape-secrets
  namespace: mcp-runescape
type: Opaque
stringData:
  PG_USER: "DATABASE USERNAME"
  PG_PASSWORD: "DATABASE PASSWORD"
  PG_HOSTNAME: "DATABASE HOSTNAME"
  PG_DATABASE: "DATABASE NAME"