services:
  runescape:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: MCP_RuneScape
    env_file:
      - .env
    ports:
      - "10001:8000"
    restart: unless-stopped