services:
  runescape:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: MCP_RuneScape
    env_file:
      - .env
    ports:
      - "10001:8000"  # MCP port
      - "8989:8989"   # Prometheus port
    restart: unless-stopped